[functions]
  directory = "netlify/functions"
[build]
  command = "cd ./client && yarn build"
[functions.screenshot]
  external_node_modules = ["chrome-aws-lambda"]
[[plugins]]
  package = "@netlify/plugin-nextjs"