[functions]
  directory = "netlify/functions"
[build]
  base = "client"
  command = "yarn build"
  publish = "out"
[functions.screenshot]
  external_node_modules = ["chrome-aws-lambda"]
[[plugins]]
  package = "@netlify/plugin-nextjs"